import type { Metadata } from "next";
import { Nunito } from "next/font/google";
@//ts-expect-error
import "./globals.css";
import { ThemeProvider } from "@/components/darkmode/theme-provider";

export const metadata: Metadata = {
  title: "Phen Sokleng - UX/UI Designer",
  description: "Generated by create next app",
};

const font = Nunito({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${font.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
